window:
  padding:
    x: 15
    y: 16
  dynamic_title: true

font:
  size: 14

key_bindings:
  - { key: Key0,     mods: Command, action: ResetFontSize }
  - { key: Equals,   mods: Command, action: IncreaseFontSize }
  - { key: Minus,    mods: Command, action: DecreaseFontSize }

  - { key: B,        mods: Alt,     chars: "\x1bb"                       } # Skip word left
  - { key: F,        mods: Alt,     chars: "\x1bf"                       } # Skip word right
  - { key: Left,     mods: Alt,     chars: "\x1bb"                       } # Skip word left
  - { key: Right,    mods: Alt,     chars: "\x1bf"                       } # Skip word right
  - { key: Left,     mods: Command, chars: "\x1bOH",   mode: AppCursor   } # Home
  - { key: Right,    mods: Command, chars: "\x1bOF",   mode: AppCursor   } # End
  - { key: Back,     mods: Command, chars: "\x15"                        } # Delete line
  - { key: Back,     mods: Alt,     chars: "\x1b\x7f"                    } # Delete word

#  - { key: Left,        mods: Alt, chars: "\x1BF" }
#  - { key: Right,        mods: Alt, chars: "\x1BB" }
