alias dbundle='ruby -I ~/projects/bundler/lib ~/projects/bundler/bin/bundle'
alias be='bundle exec'
alias beer='bundle exec rake'
alias gc='git commit -e --verbose'
alias l='ls -a'
alias m='myougiden'
alias emacs='emacs -nw'
alias vi='emacs'
